services:

  app:
    build:
      context: ../../
      dockerfile: devops/build/Dockerfile
    container_name: go-app
    ports:
      - "9091:9091"
    env_file:
      - .env
    environment:
      - DB_URL=postgres://postgres:1234@postgres:5432/myapp?sslmode=disable
    depends_on:
      - migrate
      - postgres

  postgres:
    image: postgres:16
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build:
      context: ../../
      dockerfile: devops/build/migration.Dockerfile
    container_name: goose-migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=postgres port=5432 user=postgres password=1234 dbname=myapp sslmode=disable
    entrypoint: [ "goose", "-dir", "./migrations", "up" ]
volumes:
  postgres_data:
